apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: lmw-helm-chart
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/laurawarren88/helm-chart.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: lmw-fitness
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true